{{- if and .Values.helmOperator.tls.enable .Values.helmOperator.tls.verify .Values.helmOperator.tls.caContent -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "flux.fullname" . }}-helm-tls-ca-config
data:
  ca.crt: |
{{ .Values.helmOperator.tls.caContent | indent 4 }}
{{- end -}}
